# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3ae1c420b2af2780a8d48df260160a4a67754f14ad0ecc1513ff7f47481f122b4c370bf25e45b00a5f75bb513973a14a1f88d37b530ac6acf91554512e9c5de

test:
  secret_key_base: f2890925902d204c0b38dbf6e2aa06fc4e4f800a3bc8f4ec68d9f3be82b019f62e031e9b9f757d047242a4ef6510383ba875c6d148fa8946d7b5fcf040674981

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
